services:
  4_2_first_importation-postgres:
    image: postgres:latest
    restart: unless-stopped

    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: codely
      POSTGRES_PASSWORD: c0d3ly7v
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./databases/postgres:/docker-entrypoint-initdb.d
      - ./databases/data:/docker-entrypoint-initdb.d/data

  4_2_first_importation-rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=codely
      - RABBITMQ_DEFAULT_PASS=codely

  4_2_first_importation-elasticsearch:
    image: elasticsearch:8.14.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  4_2_first_importation-logstash:
    image: logstash:8.14.3
    volumes:
      - ./etc/logstash/config:/usr/share/logstash/config
      - ./etc/logstash/pipeline:/usr/share/logstash/pipeline
      - ./etc/queries:/usr/share/logstash/queries
    ports:
      - "5044:5044"
    depends_on:
      - 4_2_first_importation-elasticsearch

volumes:
  db_data:
  prometheus_data:
