services:
  7_1_first_importation-postgres:
    image: postgres:latest
    restart: unless-stopped
    command: >
      -c max_wal_size=2GB
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: codely
      POSTGRES_PASSWORD: c0d3ly7v
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./databases/postgres:/docker-entrypoint-initdb.d
      - ./databases/data:/docker-entrypoint-initdb.d/data

  7_1_first_importation-rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=codely
      - RABBITMQ_DEFAULT_PASS=codely

volumes:
  pg_data:
  mysql_data:
